linters:
  enable-all: true
  disable:
    - exhaustivestruct # deprecated linter
    - scopelint # deprecated linter
    - gci
    - nosnakecase # deprecated linter
    - gocognit # enable at a later time
    - errcheck

linters-settings:
  lll:
    # Max line length, lines longer will be reported.
    # '\t' is counted as 1 character by default, and can be changed with the tab-width option.
    # Default: 120.
    line-length: 80
    # Tab width in spaces.
    # Default: 1
    tab-width: 1

issues:
  exclude-rules:
    - path: '(.+)_test\.go'
      linters:
        - funlen # allow long functions in test files
        - lll # allow more than 80 characters in test files